// One-off generator: produce a few hundred varied, legal middlegame FENs by
// self-playing random games and snapshotting at middlegame depth. Output is a
// static TS array baked into the hero board — no engine/AI at runtime.
//   node scripts/genHeroPositions.mjs
import { Chess } from "chess.js";
import { writeFileSync } from "node:fs";

const TARGET = 240;
const out = new Set();
let games = 0;

while (out.size < TARGET && games < 40000) {
  games++;
  const g = new Chess();
  // Snapshot at a middlegame depth — enough development to look real, not so
  // deep the board empties out.
  const targetPly = 12 + Math.floor(Math.random() * 22); // 12..33
  let ply = 0;
  while (ply < targetPly && !g.isGameOver()) {
    const moves = g.moves();
    if (!moves.length) break;
    g.move(moves[(Math.random() * moves.length) | 0]);
    ply++;
  }
  if (g.isGameOver()) continue;
  const fen = g.fen();
  const placement = fen.split(" ")[0];
  const pieces = placement.replace(/[^a-zA-Z]/g, "").length;
  if (pieces < 18) continue; // keep boards visually full
  out.add(fen);
}

const fens = [...out];
const body = `// AUTO-GENERATED by scripts/genHeroPositions.mjs — do not edit by hand.
// ${fens.length} varied, legal middlegame positions for the hero board to cycle
// through. Static data (~${Math.round(fens.join().length / 1024)}KB raw, far less gzipped); no engine/AI at runtime.

export const HERO_POSITIONS: string[] = [
${fens.map((f) => `  "${f}",`).join("\n")}
];
`;

writeFileSync(new URL("../src/sections/Landing/heroPositions.ts", import.meta.url), body);
console.log(`wrote ${fens.length} positions from ${games} games`);
